<?php require("./layout/header.php") ?>
<?php require("./layout/bodys.php") ?>
<?php require("./layout/about.php") ?>
<?php require("./layout/obj.php") ?>
<?php require("./layout/prov.php") ?>
<?php require("./layout/serv.php") ?>
<?php require("./layout/contact.php") ?>
<?php require("./layout/Map.php") ?>
<?php require("./layout/footer.php") ?>